name: ISONewEnglandCPU
channels:
  - pytorch
  - defaults
dependencies:
  - cpuonly
  - matplotlib
  - numpy
  - pandas
  - python=3.9.*
  - pip
  - pytorch
  - scikit-learn
  - scipy
  - torchvision
  - xlrd
  - pip:
    - gpytorch
